### ISSUE TITLE
make integrator spreadsheet for XR Zutphen

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/rebel_management_utilities#23]
This one is really easy: just update the local group config with a mapping from the Zutphen local group to the Zutphen municipality. We might also have to create the new spreadsheets on Nextcloud.

Once this is done inform @paulh_xr on Mattermost

**Comment by moritzcopter** [comment]
We currently have Zutphen assigned to Arnhem-Nijmegen - so could also just give @paulh_xr access to their spreadsheet?

**Comment by SamLubbers** [comment]
@moritzcopter I think it's best if we create a new spreadsheet because they are starting a new local group. If we give them access to the Arnhem-Nijmegen they'll see too many people who aren't nearby enough to their local group. This actually makes me think... should we add a `municipality` column to the spreadsheets? :thinking: 

If you go ahead with making this new spreadsheet, first contact @paulh_xr and @rindertd to ask which municipalities are relevant to them. I just heard that it's not just Zutphen.

**Comment by moritzcopter** [comment]
> should we add a municipality column to the spreadsheets? ☝️

There is a municipality column (Gemeente) ;)

> If you go ahead with making this new spreadsheet, first contact @paulh_xr and @rindertd to ask which municipalities are relevant to them. I just heard that it's not just Zutphen.

Checked with them and added those municipalities. Also created the sheet and gave them access

**Comment by SamLubbers** [comment]
@moritzcopter 

> There is a municipality column (Gemeente) ;)

That. Is. AWESOMEEE :star_struck: 

> Checked with them and added those municipalities. Also created the sheet and gave them access

Thanks so much you're the real MVP :pray:
