### ISSUE TITLE
Automatically add tech signups to tech integration sheet

### ISSUE THREAD

**Issue by fefi42** [xrnl/rebel_management_utilities#9]
Hi @moritzcopter I heard that it is possible for local groups to automatically get signups into their integration sheets.
Can we also have that for the `tech` circle?

Thanks

**Comment by moritzcopter** [comment]
Hey - yes, will look into that

**Comment by SamLubbers** [comment]
Closing this issue as it is already implemented. Thanks @moritzcopter :green_heart:
